### ISSUE TITLE
Documentation issue on page "050-tutorials/content/howto/x509_certificates/_index.md"

### ISSUE THREAD

**Issue by saifulhoque26** [gardener/documentation#44]
Can you please also describe if spec.tls field is needed after adding the label 'garden.sapcloud.io/purpose: managed-cert'
in metadata? 

If spec.tls is needed, can I put a wildcard hostname like following? Also what should be the secretName value? As I am not creating the secret. 
```
tls:
  - hosts:
    - *.ingress.<GARDENER-CLUSTER>.<GARDENER-PROJECT>.shoot.example.com
    secretName: testsecret-tls
```
---
Page: [050-tutorials/content/howto/x509_certificates/_index.md](https://github.com/gardener/documentation/edit/master/website/documentation/050-tutorials/content/howto/x509_certificates/_index.md)
don't remove the link to the page. It's required for the processor
